---
driver:
  customize:
    memory: 1024
  name: vagrant

provisioner:
  name: puppet_apply
  modules_path: nevermind
  resolve_with_librarian_puppet: true
  require_chef_for_busser: true
  require_puppet_repo: true
  update_package_repos: true
  require_puppet_collections: false
  #puppet_debug: true

platforms:
  - name: centos6
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/centos-6.6-64-nocm
  - name: centos7
    driver_plugin: vagrant
    driver_config:
      box: centos/7
  - name: ubuntu1204
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/ubuntu-12.04-64-nocm
  - name: ubuntu1404
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/ubuntu-14.04-64-nocm

suites:
  - name: go-server
  - name: go-agent
  - name: go-server-agent
